export const GET_ALL_PRODUCTS_EXAMPLE = {
  users: [
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      priceSale: 6500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      priceSale: 6500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      priceSale: 6500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      priceSale: 6500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
    {
      id: 1,
      code: 'CC-12',
      name: 'Coca Cola 1L',
      description: 'Coca Cola Familiar',
      amount: '45',
      priceBuy: 4500,
      priceSale: 6500,
      categoryType: {
        id: 2,
        code: 'MEC',
        name: 'Mecato',
      },
    },
  ],
};
export const GET_PRODUCT_EXAMPLE = {
  id: 1,
  code: 'CC-12',
  name: 'Coca Cola 1L',
  description: 'Coca Cola Familiar',
  amount: '45',
  priceBuy: 4500,
  priceSale: 6500,
  categoryType: {
    id: 2,
    code: 'MEC',
    name: 'Mecato',
  },
};
