export const GET_ALL_ACCOMMODATIONS_EXAMPLE = {
  accommodations: [
    {
      accommodationId: 1,
      code: 'CAB-1',
      name: 'Cabaña El Lago',
      description: 'Cabaña con vista al lago',
      amountPerson: 4,
      jacuzzi: true,
      amountRoom: 2,
      amountBathroom: 1,
      priceBuy: 1500.0,
      priceSale: 2000.0,
      categoryType: { id: 2, name: 'Familiar' },
      bedType: { bedTypeId: 1, name: 'Doble' },
      stateType: { stateTypeId: 1, name: 'Disponible' },
      createdAt: '2025-03-11T08:09:04.363Z',
      updatedAt: '2025-03-11T08:09:04.363Z',
    },
    {
      accommodationId: 2,
      code: 'CAB-1',
      name: 'Cabaña Montaña',
      description: 'Cabaña rústica en la montaña',
      amountPerson: 2,
      jacuzzi: false,
      amountRoom: 1,
      amountBathroom: 1,
      priceBuy: 1000.0,
      priceSale: 1500.0,
      categoryType: { id: 3, name: 'Pareja' },
      bedType: { bedTypeId: 2, name: 'Queen' },
      stateType: { stateTypeId: 2, name: 'Ocupado' },
      createdAt: '2025-03-12T10:00:00.000Z',
      updatedAt: '2025-03-12T10:00:00.000Z',
    },
  ],
};

export const GET_ACCOMMODATION_EXAMPLE = {
  accommodationId: 1,
  code: 'CAB-1',
  name: 'Cabaña El Lago',
  description: 'Cabaña con vista al lago',
  amountPerson: 4,
  jacuzzi: true,
  amountRoom: 2,
  amountBathroom: 1,
  priceBuy: 1500.0,
  priceSale: 2000.0,
  categoryType: { id: 2, name: 'Familiar' },
  bedType: { bedTypeId: 1, name: 'Doble' },
  stateType: { stateTypeId: 1, name: 'Disponible' },
  createdAt: '2025-03-11T08:09:04.363Z',
  updatedAt: '2025-03-11T08:09:04.363Z',
};
